import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Box, Button, Card, CardContent, Container, Divider, Stack, Typography } from '@mui/material';
import { AnalyticsOutlined, ArrowDownwardOutlined, ArrowForwardOutlined, BoltOutlined, CheckCircleOutline, EngineeringOutlined, InsightsOutlined, MonitorHeartOutlined, PrecisionManufacturingOutlined, PsychologyOutlined, QueryStatsOutlined, RecommendOutlined, SensorsOutlined, ShieldOutlined, SpeedOutlined, TimelineOutlined } from '@mui/icons-material';
import { motion, useInView } from 'framer-motion';
import paperMillHero from '../assets/paper-mill-hero.svg';

const red = '#C8102E';
const navy = '#1E293B';
const sectionSx = { py: { xs: 8, md: 12 } };
const fadeUp = { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.2 }, transition: { duration: 0.45 } };

function SectionHeading({ eyebrow, title, description, center = false }) {
  return <Box sx={{ maxWidth: 650, mb: 5, mx: center ? 'auto' : 0, textAlign: center ? 'center' : 'left' }}>
    <Typography variant="overline" sx={{ color: red, fontWeight: 700, letterSpacing: '.12em' }}>{eyebrow}</Typography>
    <Typography variant="h3" sx={{ mt: .75, fontSize: { xs: '2rem', md: '2.65rem' }, lineHeight: 1.16 }}>{title}</Typography>
    {description && <Typography color="text.secondary" sx={{ mt: 1.5, fontSize: 16, lineHeight: 1.7 }}>{description}</Typography>}
  </Box>;
}

function Stat({ value, label }) {
  const ref = useRef(null);
  const visible = useInView(ref, { once: true, amount: 0.6 });
  const [shown, setShown] = useState(0);
  const numeric = Number.parseFloat(value);
  const suffix = value.replace(String(numeric), '');
  useEffect(() => {
    if (!visible) return undefined;
    const started = performance.now();
    const timer = setInterval(() => {
      const progress = Math.min((performance.now() - started) / 850, 1);
      setShown(numeric * progress);
      if (progress === 1) clearInterval(timer);
    }, 16);
    return () => clearInterval(timer);
  }, [visible, numeric]);
  return <Box ref={ref} sx={{ textAlign: 'center' }}><Typography variant="h2" sx={{ fontSize: { xs: '2.6rem', md: '3.35rem' }, color: red, lineHeight: 1 }}>{numeric % 1 ? shown.toFixed(1) : Math.round(shown)}{suffix}</Typography><Typography color="text.secondary" fontWeight={600} mt={1}>{label}</Typography></Box>;
}

export default function LoginPage() {
  const navigate = useNavigate();
  const scrollToOverview = () => document.getElementById('why-paperai')?.scrollIntoView({ behavior: 'smooth' });
  const primaryButtonSx = { px: 3, py: 1.35, borderRadius: 1.25, boxShadow: '0 8px 20px rgba(200,16,46,.25)', '&:hover': { bgcolor: '#9F0D25', boxShadow: '0 11px 26px rgba(200,16,46,.33)', transform: 'translateY(-1px)' }, transition: 'background-color .2s ease, box-shadow .2s ease, transform .2s ease' };
  const benefits = [{ icon: <PsychologyOutlined />, title: 'AI Prediction', text: 'Predict future basis weight before a deviation reaches the reel.' }, { icon: <RecommendOutlined />, title: 'Smart Recommendation Engine', text: 'Receive prioritized corrective actions in the moment they matter.' }, { icon: <AnalyticsOutlined />, title: 'Industrial Analytics', text: 'Monitor quality, process stability, and production performance in one view.' }];
  const features = [{ title: 'Real-Time Prediction', text: 'Use live process conditions to surface upcoming basis weight deviation before it affects paper quality.', icon: <TimelineOutlined />, visual: 'Live process intelligence' }, { title: 'Historical Trend Analysis', text: 'Put every grade change in context with clear, operator-friendly production trends.', icon: <QueryStatsOutlined />, visual: 'Actionable production history' }, { title: 'Risk Detection', text: 'Translate complex sensor behavior into clear safe, warning, and critical process signals.', icon: <ShieldOutlined />, visual: 'Focused risk visibility' }, { title: 'Operator Recommendations', text: 'Turn predictive insight into practical adjustment guidance for a more consistent run.', icon: <RecommendOutlined />, visual: 'Decisions with confidence' }];
  const workflow = [{ icon: <SensorsOutlined />, label: 'Sensors' }, { icon: <PsychologyOutlined />, label: 'AI Engine' }, { icon: <InsightsOutlined />, label: 'Prediction' }, { icon: <RecommendOutlined />, label: 'Recommendation' }, { icon: <EngineeringOutlined />, label: 'Operator' }];
  const enterprise = [{ icon: <PrecisionManufacturingOutlined />, title: 'Industrial grade', text: 'Designed around mill workflows.' }, { icon: <SpeedOutlined />, title: 'Fast prediction', text: 'Insights when operators need them.' }, { icon: <CheckCircleOutline />, title: 'High accuracy', text: 'Focused on quality stability.' }, { icon: <BoltOutlined />, title: 'AI powered', text: 'Practical intelligence, not noise.' }, { icon: <MonitorHeartOutlined />, title: 'Easy integration', text: 'Fits modern process environments.' }];

  return <Box sx={{ minHeight: '100vh', bgcolor: '#fff', color: '#0F172A', scrollBehavior: 'smooth' }}>
    <Box component="header" sx={{ position: 'absolute', zIndex: 2, width: '100%', color: '#fff' }}><Container maxWidth="lg" sx={{ height: 80, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><Stack direction="row" alignItems="center" spacing={1.25}><Box sx={{ width: 35, height: 35, display: 'grid', placeItems: 'center', bgcolor: red, borderRadius: 1 }}><MonitorHeartOutlined fontSize="small" /></Box><Typography fontWeight={700} fontSize={19}>PaperAI</Typography></Stack><Typography variant="caption" sx={{ display: { xs: 'none', sm: 'block' }, letterSpacing: '.1em', color: 'rgba(255,255,255,.75)' }}>PROCESS INTELLIGENCE</Typography></Container></Box>

    <Box component="section" sx={{ minHeight: '100vh', display: 'grid', placeItems: 'center', position: 'relative', color: '#fff', overflow: 'hidden', backgroundImage: `linear-gradient(90deg, rgba(15,23,42,.92), rgba(15,23,42,.72)), url(${paperMillHero})`, backgroundSize: 'cover', backgroundPosition: 'center' }}>
      <Container maxWidth="lg" sx={{ pt: 10, pb: 7, position: 'relative' }}><motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }}><Typography variant="overline" sx={{ color: '#F7B5C0', fontWeight: 700, letterSpacing: '.14em' }}>PREDICTIVE QUALITY INTELLIGENCE</Typography><Typography sx={{ fontSize: { xs: '4rem', sm: '5.5rem', md: '6.75rem' }, lineHeight: .95, fontWeight: 700, letterSpacing: '-.055em', mt: 1 }}>PaperAI</Typography><Typography sx={{ maxWidth: 790, fontSize: { xs: '1.65rem', md: '2.6rem' }, lineHeight: 1.2, fontWeight: 600, mt: 2.5 }}>AI Powered Grade Change Intelligence</Typography><Typography sx={{ maxWidth: 610, mt: 2.5, color: 'rgba(255,255,255,.8)', fontSize: { xs: 16, md: 18 }, lineHeight: 1.75 }}>Predict basis weight deviations before they happen. Optimize paper quality. Reduce production losses. Increase operational efficiency using AI.</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} mt={4}><Button variant="contained" size="large" endIcon={<ArrowForwardOutlined />} onClick={() => navigate('/dashboard')} sx={primaryButtonSx}>Get Started</Button><Button variant="outlined" size="large" endIcon={<ArrowDownwardOutlined />} onClick={scrollToOverview} sx={{ px: 3, py: 1.35, borderColor: 'rgba(255,255,255,.55)', color: '#fff', borderRadius: 1.25, '&:hover': { borderColor: '#fff', bgcolor: 'rgba(255,255,255,.08)' } }}>Learn More</Button></Stack></motion.div></Container>
    </Box>

    <Container id="why-paperai" maxWidth="lg" component="section" sx={sectionSx}><motion.div {...fadeUp}><SectionHeading center eyebrow="WHY PAPERAI" title="Clarity for every grade change" description="A purpose-built intelligence layer that connects process data, predictive models, and operator action." /></motion.div><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' }, gap: 2.5 }}>{benefits.map((item) => <Card component={motion.div} whileHover={{ y: -5 }} transition={{ duration: .2 }} key={item.title} sx={{ borderRadius: 2, boxShadow: '0 5px 20px rgba(15,23,42,.06)', '&:hover': { boxShadow: '0 14px 30px rgba(15,23,42,.12)' } }}><CardContent sx={{ p: 3.25 }}><Box sx={{ width: 48, height: 48, display: 'grid', placeItems: 'center', borderRadius: 1.5, color: red, bgcolor: '#FDECEF', mb: 2.5 }}>{item.icon}</Box><Typography variant="h6">{item.title}</Typography><Typography color="text.secondary" variant="body2" lineHeight={1.7} mt={1}>{item.text}</Typography></CardContent></Card>)}</Box></Container>

    <Box component="section" sx={{ ...sectionSx, bgcolor: '#F5F7FA' }}><Container maxWidth="lg"><motion.div {...fadeUp}><SectionHeading eyebrow="PRODUCT CAPABILITIES" title="Built for the production floor" description="PaperAI keeps the most important process signals understandable, timely, and actionable." /></motion.div><Stack spacing={{ xs: 6, md: 8 }}>{features.map((feature, index) => <Box component={motion.div} {...fadeUp} key={feature.title} sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: { xs: 3, md: 8 }, alignItems: 'center' }}><Box sx={{ order: { md: index % 2 ? 2 : 1 } }}><Box sx={{ minHeight: { xs: 210, md: 260 }, bgcolor: navy, borderRadius: 2, p: { xs: 3, md: 4 }, color: '#fff', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', position: 'relative', overflow: 'hidden', boxShadow: '0 12px 28px rgba(15,23,42,.18)' }}><Box sx={{ position: 'absolute', top: 30, right: 30, width: 110, height: 110, border: '1px solid rgba(255,255,255,.22)', borderRadius: '50%' }} /><Box sx={{ position: 'absolute', top: 65, right: 65, width: 40, height: 40, bgcolor: red, borderRadius: '50%' }} /><Typography variant="overline" sx={{ color: '#F7B5C0', fontWeight: 700 }}>{String(index + 1).padStart(2, '0')}</Typography><Typography variant="h5">{feature.visual}</Typography></Box></Box><Box sx={{ order: { md: index % 2 ? 1 : 2 } }}><Box sx={{ color: red, mb: 1.5 }}>{feature.icon}</Box><Typography variant="h4" sx={{ fontSize: { xs: '1.8rem', md: '2.25rem' } }}>{feature.title}</Typography><Typography color="text.secondary" sx={{ mt: 1.5, lineHeight: 1.75 }}>{feature.text}</Typography></Box></Box>)}</Stack></Container></Box>

    <Container component="section" maxWidth="lg" sx={sectionSx}><motion.div {...fadeUp}><SectionHeading center eyebrow="MEASURABLE IMPACT" title="Engineered for stable production" /></motion.div><Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2, 1fr)', md: 'repeat(4, 1fr)' }, gap: { xs: 4, md: 2 } }}><Stat value="99.5%" label="Prediction Accuracy" /><Stat value="40%" label="Reduction in Quality Loss" /><Stat value="25%" label="Faster Grade Change" /><Stat value="24/7" label="Continuous Monitoring" /></Box></Container>

    <Box component="section" sx={{ ...sectionSx, bgcolor: '#F5F7FA' }}><Container maxWidth="lg"><motion.div {...fadeUp}><SectionHeading center eyebrow="HOW IT WORKS" title="From process signal to operator action" /></motion.div><Box sx={{ display: 'flex', flexDirection: { xs: 'column', md: 'row' }, alignItems: { xs: 'stretch', md: 'center' }, justifyContent: 'space-between', gap: { xs: 1, md: 0 } }}>{workflow.map((step, index) => <Box key={step.label} sx={{ display: 'contents' }}><Box sx={{ textAlign: 'center', minWidth: 110 }}><Box sx={{ width: 58, height: 58, mx: 'auto', borderRadius: '50%', display: 'grid', placeItems: 'center', color: red, bgcolor: '#fff', border: '1px solid #E2E8F0', boxShadow: '0 3px 10px rgba(15,23,42,.05)' }}>{step.icon}</Box><Typography fontWeight={700} variant="body2" mt={1.25}>{step.label}</Typography></Box>{index < workflow.length - 1 && <Box sx={{ height: { xs: 25, md: 1 }, width: { xs: 1, md: '9%' }, mx: { xs: 'auto', md: 0 }, bgcolor: '#CBD5E1' }} />}</Box>)}</Box></Container></Box>

    <Container component="section" maxWidth="lg" sx={sectionSx}><motion.div {...fadeUp}><SectionHeading center eyebrow="WHY CHOOSE PAPERAI" title="Enterprise intelligence without the noise" /></motion.div><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(5, 1fr)' }, gap: 1.5 }}>{enterprise.map((item) => <Card key={item.title} sx={{ borderRadius: 1.5, boxShadow: 'none', bgcolor: '#F8FAFC' }}><CardContent sx={{ p: 2.25 }}><Box sx={{ color: red, mb: 1 }}>{item.icon}</Box><Typography fontWeight={700} variant="body2">{item.title}</Typography><Typography variant="caption" color="text.secondary" display="block" lineHeight={1.5} mt={.5}>{item.text}</Typography></CardContent></Card>)}</Box></Container>

    <Box component="section" sx={{ py: { xs: 8, md: 10 }, bgcolor: navy, color: '#fff', textAlign: 'center' }}><Container maxWidth="md"><Typography variant="overline" sx={{ color: '#F7B5C0', fontWeight: 700, letterSpacing: '.12em' }}>START WITH PAPERAI</Typography><Typography variant="h3" sx={{ mt: 1, fontSize: { xs: '2.1rem', md: '3rem' } }}>Ready to optimize your paper manufacturing?</Typography><Typography sx={{ color: 'rgba(255,255,255,.72)', mt: 1.5, maxWidth: 560, mx: 'auto', lineHeight: 1.7 }}>Bring predictive quality intelligence to the moments that shape production performance.</Typography><Button variant="contained" size="large" endIcon={<ArrowForwardOutlined />} onClick={() => navigate('/dashboard')} sx={{ ...primaryButtonSx, mt: 3.5 }}>Get Started</Button></Container></Box>

    <Box component="footer" sx={{ bgcolor: '#111B29', color: 'rgba(255,255,255,.7)', py: 3 }}><Container maxWidth="lg" sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, gap: 1, alignItems: { xs: 'flex-start', sm: 'center' }, justifyContent: 'space-between' }}><Stack direction="row" alignItems="center" spacing={1}><MonitorHeartOutlined sx={{ color: red }} fontSize="small" /><Typography color="#fff" fontWeight={700}>PaperAI</Typography><Divider orientation="vertical" flexItem sx={{ borderColor: 'rgba(255,255,255,.2)' }} /><Typography variant="caption">AI Hackathon</Typography></Stack><Typography variant="caption">Built using React · FastAPI · XGBoost · Material UI</Typography></Container></Box>
  </Box>;
}
